### ISSUE TITLE
Does not scrape list price for items on sale

### ISSUE THREAD

**Issue by immist** [FranzSkuffka/amazon-review-scraper#2]
For items on sale (like http://www.amazon.com/MWF-Replacement-Refrigerator-Pure-Line/dp/B00YV210RA/ref=cm_cr_pr_product_top?ie=UTF8), the script does not scrape the list price (or sale price), returning '0' instead of list (or sale) price.

Regular products are marked up with '#priceblock_ourprice', while products on sale are marked up with a price table missing the mentioned ID.

**Comment by FranzSkuffka** [comment]
Pull requests are welcome.
